name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment/
        with:
          env_type: "test"

      - name: Performing unit tests
        uses: ./.github/actions/run-tests/

      - name: Setup Production Environment
        uses: ./.github/actions/setup-environment/
        with:
          env_type: "prod"

      - name: Deploy Laravel App
        uses: ./.github/actions/deploy-laravel/
