name: Run Tests & Lint

on:
  workflow_call:  # Allows it to be called from another workflow
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Environment for Testing
        run: |
          if [ -f ".env.testing" ]; then
            cp .env.testing .env
            echo "✅ .env.testing copied to .env"
          else
            echo "⚠ .env.testing not found. Skipping environment setup."
          fi

      - name: Run Database Migrations
        run: php artisan migrate --env=testing --force

      - name: Run Unit Tests
        run: php artisan test
        env:
          APP_ENV: testing
